services:
  user-service:
    container_name: user-service
    build:
      context: .
      target: ${BUILD_TARGET:-dev}
    volumes:
      - ~/.m2:/root/.m2
      - ./:/app
    networks:
      - ms
    depends_on:
      mongo-db:
        condition: service_healthy

  mongo-db:
    container_name: mongo-docker
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - ms
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'echo ''db.runCommand("ping").ok'' | mongo --username user --password password --authenticationDatabase admin --quiet',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  ms:
    external: true
